[package]
name = "typos-lsp"
version = "0.1.29"
edition = "2021"

[dependencies]
tracing-subscriber = { version = "0.3.16", default-features = false, features = ["env-filter", "fmt", "smallvec", "std"] }
tower-lsp = "0.20.0"
tracing = "0.1.37"
tokio = { version = "1.41", features = ["macros", "rt-multi-thread", "io-std", "io-util"] }
serde_json = "1.0"
anyhow = "1.0"
bstr = "1.10"
itertools = "0.13.0"
env_logger = "0.11.5"
typos = "0.10"
typos-cli = "1.27"
serde = { version = "1.0", features = ["derive"] }
ignore = "0.4.20"
matchit = "0.8.4"
shellexpand = "3.1.0"
regex = "1.11.1"
once_cell = "1.20.2"

[dev-dependencies]
test-log = { version = "0.2.16", features = ["trace"] }
httparse = "1.9"
similar-asserts = "1.4"
